name: CI/CD for Netlify Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérification du code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configuration de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Utilisez la version de Node.js compatible avec votre projet

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Étape 4 : Construire le projet
      - name: Build the project
        run: npm run build

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      # Étape 6 : Déployer sur Netlify
      - name: Link to Netlify site
        run: |
          netlify link --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }}

      - name: Deploy to Netlify
        run: netlify deploy --prod --dir=.next --site ${{ secrets.NETLIFY_SITE_ID }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
